### ISSUE TITLE
Encapsulate SCPI parameters in quotes for SSID and password fields.

### ISSUE THREAD

**Issue by cptkoolbeenz** [daqifi/daqifi-desktop#71]
Commands with text parameters that could contain symbols should be sent with quotes around the parameters.  For example:
SYSTem:COMMunicate:LAN:SSID "Tesla"
SYSTem:COMMunicate:LAN:PASs "P@$$w0Rd"

**Comment by codedecoded01723** [comment]
@cptkoolbeenz , We have checked through backend by debugging it , it is already sending the password and SSID command in double quotes only , if any this thing else specific required from the is ticket we can implement that otherwise we can close this ticket .

**Comment by cptkoolbeenz** [comment]
Okay, good.  I think I got confused during our last debug session - thinking the SSID/password was not getting sent properly.  I think it was working but your virtual machine was on a different subnet.
